name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and start the application
      run: |
        docker-compose up --build -d

    - name: Get container IP and port
      id: container_info
      run: |
        CONTAINER_ID=$(docker-compose ps -q)
        CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CONTAINER_ID)
        CONTAINER_PORTS=$(docker inspect -f '{{range $p, $conf := .NetworkSettings.Ports}}{{$p}}{{end}}' $CONTAINER_ID)
        CONTAINER_PORT=$(echo $CONTAINER_PORTS | cut -d '/' -f 1)
        echo "The application is running at http://$CONTAINER_IP:$CONTAINER_PORT"
        echo "::set-output name=ip::$CONTAINER_IP"
        echo "::set-output name=port::$CONTAINER_PORT"

    - name: Access container
      run: |
        docker-compose exec -it service_name bash
