name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and start the application
      run: |
        docker-compose up --build -d

    - name: Get container information
      id: container_info
      run: |
        # Retrieve the container ID
        CONTAINER_ID=$(docker-compose ps -q)

        # Retrieve the container IP address
        CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CONTAINER_ID)

        # Retrieve the application port
        APP_PORT=$(docker port $CONTAINER_ID 8085/tcp | cut -d':' -f2)

        # Retrieve the PHPMyAdmin port
        PHPMYADMIN_PORT=$(docker port $CONTAINER_ID 9095/tcp | cut -d':' -f2)

        # Print the application and PHPMyAdmin URLs
        echo "The application is running at http://$CONTAINER_IP:$APP_PORT"
        echo "PHPMyAdmin is running at http://$CONTAINER_IP:$PHPMYADMIN_PORT"

        # Write the output to environment files
        echo "container_ip=$CONTAINER_IP" >> $GITHUB_OUTPUT
        echo "app_port=$APP_PORT" >> $GITHUB_OUTPUT
        echo "phpmyadmin_port=$PHPMYADMIN_PORT" >> $GITHUB_OUTPUT

    - name: Access application
      run: |
        echo "Accessing application at http://${{ steps.container_info.outputs.container_ip }}:${{ steps.container_info.outputs.app_port }}"
        echo "Accessing PHPMyAdmin at http://${{ steps.container_info.outputs.container_ip }}:${{ steps.container_info.outputs.phpmyadmin_port }}"

    - name: Access container
      run: |
        docker-compose exec -it service_name bash
