name: Application CI/CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and start the application
      env:
        DB_CONNECTION: testinho-mariadb
        DB_HOST: testinho-mariadb
        DB_PORT: 3306
        DB_DATABASE: vogue
        DB_USERNAME: root
        DB_PASSWORD: root
        APP_PORT: 8085
        PHPMYADMIN_PORT: 9095
      run: |
        docker-compose -f docker-compose.yml up --build -d

    - name: Get container information
      id: container_info
      run: |
        # Wait for the application to start
        sleep 10

        # Retrieve the container ID for the MariaDB service
        MARIADB_CONTAINER_ID=$(docker-compose ps -q testinho-mariadb)

        # Retrieve the IP address of the MariaDB container
        MARIADB_CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $MARIADB_CONTAINER_ID)

        # Print the MariaDB and PHPMyAdmin URLs
        echo "The MariaDB service is running at $MARIADB_CONTAINER_IP:3306"
        echo "PHPMyAdmin is running at http://$MARIADB_CONTAINER_IP:9095"

        # Write the output to environment files
        echo "mariadb_container_ip=$MARIADB_CONTAINER_IP" >> $GITHUB_OUTPUT
        echo "app_port=8085" >> $GITHUB_OUTPUT
        echo "phpmyadmin_port=9095" >> $GITHUB_OUTPUT

    - name: Access MariaDB and PHPMyAdmin
      run: |
        echo "Accessing MariaDB at ${{ steps.container_info.outputs.mariadb_container_ip }}:3306"
        echo "Accessing PHPMyAdmin at http://${{ steps.container_info.outputs.mariadb_container_ip }}:${{ steps.container_info.outputs.phpmyadmin_port }}"

    - name: Access container
      run: |
        docker-compose exec -it testinho-mariadb bash
