name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and start the application
      run: |
        docker-compose up --build -d

    - name: Get container IP and port
      id: container_info
      run: |
        CONTAINER_ID=$(docker-compose ps -q)
        CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CONTAINER_ID)
        APP_PORT=8085
        PHPMYADMIN_PORT=9095
        echo "The application is running at http://$CONTAINER_IP:$APP_PORT"
        echo "PHPMyAdmin is running at http://$CONTAINER_IP:$PHPMYADMIN_PORT"
        echo "::set-output name=ip::$CONTAINER_IP"
        echo "::set-output name=app_port::$APP_PORT"
        echo "::set-output name=phpmyadmin_port::$PHPMYADMIN_PORT"

    - name: Access application
      run: |
        echo "Accessing application at http://${{ steps.container_info.outputs.ip }}:${{ steps.container_info.outputs.app_port }}"
        echo "Accessing PHPMyAdmin at http://${{ steps.container_info.outputs.ip }}:${{ steps.container_info.outputs.phpmyadmin_port }}"

    - name: Access container
      run: |
        docker-compose exec -it service_name bash
