# Retrieve the container ID
CONTAINER_ID=$(docker-compose ps -q)

# Retrieve the container IP address
CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CONTAINER_ID)

# Retrieve the application port
APP_PORT=$(docker port $CONTAINER_ID 8085/tcp | cut -d':' -f2)

# Retrieve the PHPMyAdmin port
PHPMYADMIN_PORT=$(docker port $CONTAINER_ID 9095/tcp | cut -d':' -f2)

# Print the application and PHPMyAdmin URLs
echo "The application is running at http://$CONTAINER_IP:$APP_PORT"
echo "PHPMyAdmin is running at http://$CONTAINER_IP:$PHPMYADMIN_PORT"

# Write the output to environment files
echo "container_ip=$CONTAINER_IP" >> $GITHUB_OUTPUT
echo "app_port=$APP_PORT" >> $GITHUB_OUTPUT
echo "phpmyadmin_port=$PHPMYADMIN_PORT" >> $GITHUB_OUTPUT
